---
title: Titre
timezone: UTC
baseurl: 0bartm.github.io/Flatfile
collections:
  collection:
    title: Collection
    output: true
    permalink: "../cours/CompteRendu.md"
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
