---
title: Titre
timezone: UTC
collections:
  collection:
    title: Collection
    output: true
    permalink: "../cours/CompteRendu.md"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
